Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
    - 'context'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*_spec.rb'
